version: '3.8'

services:
  db:
    image: mysql:8.0.42
    restart: always
    container_name: mysql_titanic
    environment:
      MYSQL_DATABASE: my_titanic
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask:
    build: .
    container_name: flask_app
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: P@ssw0rd
      DB_NAME: my_titanic
    # 移除整個 .:/app 的 volume，避免覆蓋
    # volumes:
    #   - ./templates:/app/templates

volumes:
  db_data:
